# config/_default/params.toml

defaultAppearance = "light"

robots = "noindex"

header.showTitle = true

homepage.layout = "custom"

footer.showThemeAttribution	= true
autoSwitchAppearance = false
# footer.showAppearanceSwitcher = true

copyright = "BRB, learning how to code again ğŸ‘©â€ğŸ’»"

homepage.showRecent = true
