# config/_default/params.toml

# colorScheme = "congo"

defaultAppearance = "light"

robots = "noindex"

header.showTitle = false

homepage.layout = "profile"

footer.showThemeAttribution	= true
autoSwitchAppearance = false
# footer.showAppearanceSwitcher = true

copyright = "BRB, learning how to code again ğŸ‘©â€ğŸ’»"
